#!/bin/sh
rm -f config.cache
rm -f acconfig.h
echo "- aclocal."
aclocal -I m4
echo "- autoconf."
autoconf
echo "- acconfig."
acconfig
echo "- autoheader."
autoheader
echo "- automake."
automake -a
exit
